//
//  InstructionTable.h
//  z80asm
//
//  Created by Rafał Białek on 03/11/2016.
//  Copyright © 2016 Rafał Białek. All rights reserved.
//

#ifndef InstructionTable_h
#define InstructionTable_h

#include <string>
#include <unordered_map>

#include "Exceptions.h"

using namespace std;

typedef const unordered_map<string, string> InstructionSet;

static InstructionSet z80instructions = {
    {"ld a,a","7f"},\
    {"ld a,b","78"},\
    {"ld a,c","79"},\
    {"ld a,d","7a"},\
    {"ld a,e","7b"},\
    {"ld a,h","7c"},\
    {"ld a,l","7d"},\
    {"ld a,(hl)","7e"},\
    {"ld a,(bc)","0a"},\
    {"ld a,(de)","1a"},\
    {"ld a,(%i)","3a%w"},\
    {"ld a,(ix+%i)","dd7e%b"},\
    {"ld a,(iy+%i)","fd7e%b"},\
    {"ld b,a","47"},\
    {"ld b,b","40"},\
    {"ld b,c","41"},\
    {"ld b,d","42"},\
    {"ld b,e","43"},\
    {"ld b,h","44"},\
    {"ld b,l","45"},\
    {"ld b,(hl)","46"},\
    {"ld b,(ix+%i)","dd46%b"},\
    {"ld b,(iy+%i)","fd46%b"},\
    {"ld c,a","4f"},\
    {"ld c,b","48"},\
    {"ld c,c","49"},\
    {"ld c,d","4a"},\
    {"ld c,e","4b"},\
    {"ld c,h","4c"},\
    {"ld c,l","4d"},\
    {"ld c,(hl)","4e"},\
    {"ld c,(ix+%i)","dd4e%b"},\
    {"ld c,(iy+%i)","fd4e%b"},\
    {"ld d,a","57"},\
    {"ld d,b","50"},\
    {"ld d,c","51"},\
    {"ld d,d","52"},\
    {"ld d,e","53"},\
    {"ld d,h","54"},\
    {"ld d,l","55"},\
    {"ld d,(hl)","56"},\
    {"ld d,(ix+%i)","dd56%b"},\
    {"ld d,(iy+%i)","fd56%b"},\
    {"ld e,a","5f"},\
    {"ld e,b","58"},\
    {"ld e,c","59"},\
    {"ld e,d","5a"},\
    {"ld e,e","5b"},\
    {"ld e,h","5c"},\
    {"ld e,l","5d"},\
    {"ld e,(hl)","5e"},\
    {"ld e,(ix+%i)","dd5e%b"},\
    {"ld e,(iy+%i)","fd5e%b"},\
    {"ld h,a","67"},\
    {"ld h,b","60"},\
    {"ld h,c","61"},\
    {"ld h,d","62"},\
    {"ld h,e","63"},\
    {"ld h,h","64"},\
    {"ld h,l","65"},\
    {"ld h,(hl)","66"},\
    {"ld h,(ix+%i)","dd66%b"},\
    {"ld h,(iy+%i)","fd66%b"},\
    {"ld l,a","6f"},\
    {"ld l,b","68"},\
    {"ld l,c","69"},\
    {"ld l,d","6a"},\
    {"ld l,e","6b"},\
    {"ld l,h","6c"},\
    {"ld l,l","6d"},\
    {"ld l,(hl)","6e"},\
    {"ld l,(ix+%i)","dd6e%b"},\
    {"ld l,(iy+%i)","fd6e%b"},\
    {"ld (hl),a","77"},\
    {"ld (hl),b","70"},\
    {"ld (hl),c","71"},\
    {"ld (hl),d","72"},\
    {"ld (hl),e","73"},\
    {"ld (hl),h","74"},\
    {"ld (hl),l","75"},\
    {"ld (ix+%i),a","dd77%b"},\
    {"ld (ix+%i),b","dd70%b"},\
    {"ld (ix+%i),c","dd71%b"},\
    {"ld (ix+%i),d","dd72%b"},\
    {"ld (ix+%i),e","dd73%b"},\
    {"ld (ix+%i),h","dd74%b"},\
    {"ld (ix+%i),l","dd75%b"},\
    {"ld (ix+%i),%i","dd76%b%b"},\
    {"ld (iy+%i),a","fd77%b"},\
    {"ld (iy+%i),b","fd70%b"},\
    {"ld (iy+%i),c","fd71%b"},\
    {"ld (iy+%i),d","fd72%b"},\
    {"ld (iy+%i),e","fd73%b"},\
    {"ld (iy+%i),h","fd74%b"},\
    {"ld (iy+%i),l","fd75%b"},\
    {"ld (iy+%i),%i","fd76%b%b"},\
    {"ld a,%i","3e%b"},\
    {"ld b,%i","06%b"},\
    {"ld c,%i","0e%b"},\
    {"ld d,%i","16%b"},\
    {"ld e,%i","1e%b"},\
    {"ld h,%i","26%b"},\
    {"ld l,%i","2e%b"},\
    {"ld (hl),%i","36%b"},\
    {"ld (ix+%i),%i","dd36%b%b"},\
    {"ld (iy+%i),%i","fd36%b%b"},\
    {"ld (bc),a","02"},\
    {"ld (de),a","12"},\
    {"ld (%i),a","32%w"},\
    {"ld bc,%i","01%w"},\
    {"ld de,%i","11%w"},\
    {"ld hl,%i","21%w"},\
    {"ld sp,%i","31%w"},\
    {"ld ix,%i","dd21%w"},\
    {"ld iy,%i","fd21%w"},\
    {"ld hl,(%i)","2a%w"},\
    {"ld bc,(%i)","ed4b%w"},\
    {"ld de,(%i)","ed5b%w"},\
    {"ld hl,(%i)","ed6b%w"},\
    {"ld sp,(%i)","ed7b%w"},\
    {"ld ix,(%i)","dd2a%w"},\
    {"ld iy,(%i)","fd2a%w"},\
    {"ld (%i),hl","22%w"},\
    {"ld (%i),bc","ed43%w"},\
    {"ld (%i),de","ed53%w"},\
    {"ld (%i),hl","ed6b%w"},\
    {"ld (%i),ix","dd22%w"},\
    {"ld (%i),iy","dd22%w"},\
    {"ld (%i),sp","ed73%w"},\
    {"ld sp,hl","f9"},\
    {"ld sp,ix","ddf9"},\
    {"ld sp,iy","fdf9"},\
    {"ex de,hl","eb"},\
    {"ex (sp),hl","e3"},\
    {"ex (sp),ix","dde3"},\
    {"ex (sp),iy","fde3"},\
    {"ex af,af'","08"},\
    {"exx","d9"},\
    {"add a,a","87"},\
    {"add a,b","80"},\
    {"add a,c","81"},\
    {"add a,d","82"},\
    {"add a,e","83"},\
    {"add a,h","84"},\
    {"add a,l","85"},\
    {"add a,(hl)","86"},\
    {"add a,(ix+%i)","dd86%b"},\
    {"add a,(iy+%i)","fd86%b"},\
    {"add a,%i","c6%b"},\
    {"adc a,a","8f"},\
    {"adc a,b","88"},\
    {"adc a,c","89"},\
    {"adc a,d","8a"},\
    {"adc a,e","8b"},\
    {"adc a,h","8c"},\
    {"adc a,l","8d"},\
    {"adc a,(hl)","8e"},\
    {"adc a,(ix+%i)","dd8e%b"},\
    {"adc a,(iy+%i)","fd8e%b"},\
    {"adc a,%i","ce%b"},\
    {"sub a","97"},\
    {"sub b","90"},\
    {"sub c","91"},\
    {"sub d","92"},\
    {"sub e","93"},\
    {"sub h","94"},\
    {"sub l","95"},\
    {"sub (hl)","96"},\
    {"sub (ix+%i)","dd96%b"},\
    {"sub (iy+%i)","fd96%b"},\
    {"sub %i","d6%b"},\
    {"sbc a","9f"},\
    {"sbc b","98"},\
    {"sbc c","99"},\
    {"sbc d","9a"},\
    {"sbc e","9b"},\
    {"sbc h","9c"},\
    {"sbc l","9d"},\
    {"sbc (hl)","9e"},\
    {"sbc (ix+%i)","dd9e%b"},\
    {"sbc (iy+%i)","fd9e%b"},\
    {"sbc %i","de%b"},\
    {"add hl,bc","09"},\
    {"add hl,de","19"},\
    {"add hl,hl","29"},\
    {"add hl,sp","39"},\
    {"add ix,bc","dd09"},\
    {"add ix,de","dd19"},\
    {"add ix,ix","dd29"},\
    {"add ix,sp","dd39"},\
    {"add iy,bc","fd09"},\
    {"add iy,de","fd19"},\
    {"add iy,iy","fd29"},\
    {"add iy,sp","fd39"},\
    {"adc hl,bc","ed4a"},\
    {"adc hl,de","ed5a"},\
    {"adc hl,hl","ed6a"},\
    {"adc hl,sp","ed7a"},\
    {"sbc hl,bc","ed42"},\
    {"sbc hl,de","ed52"},\
    {"sbc hl,hl","ed62"},\
    {"sbc hl,sp","ed72"},\
    {"di","f3"},\
    {"ei","fb"},\
    {"im 0","ed46"},\
    {"im 1","ed56"},\
    {"im 2","ed5e"},\
    {"ld a,i","ed57"},\
    {"ld i,a","ed47"},\
    {"ld a,r","ed5f"},\
    {"ld r,a","ed4f"},\
    {"nop","00"},\
    {"hlt","76"},\
    {"inc a","3c"},\
    {"inc b","04"},\
    {"inc c","0c"},\
    {"inc d","14"},\
    {"inc e","1c"},\
    {"inc h","24"},\
    {"inc l","2c"},\
    {"inc (hl)","34"},\
    {"inc (ix+%i)","dd34%b"},\
    {"inc (iy+%i)","fd34%b"},\
    {"dec a","3d"},\
    {"dec b","05"},\
    {"dec c","0d"},\
    {"dec d","15"},\
    {"dec e","1d"},\
    {"dec h","25"},\
    {"dec l","2d"},\
    {"dec (hl)","35"},\
    {"dec (ix+%i)","dd35%b"},\
    {"dec (iy+%i)","fd35%b"},\
    {"inc bc","03"},\
    {"inc de","13"},\
    {"inc hl","23"},\
    {"inc sp","33"},\
    {"inc ix","dd23"},\
    {"inc iy","fd23"},\
    {"dec bc","0b"},\
    {"dec de","1b"},\
    {"dec hl","2b"},\
    {"dec sp","3b"},\
    {"dec ix","dd2b"},\
    {"dec iy","fd2b"},\
    {"daa","27"},\
    {"cpl","2f"},\
    {"scf","37"},\
    {"ccf","3f"},\
    {"neg","ed44"},\
    {"rlca","07"},\
    {"rrca","0f"},\
    {"rla","17"},\
    {"rra","1f"},\
    {"rld","ed6f"},\
    {"rrd","ed67"},\
    {"rlc a","cb07"},\
    {"rlc b","cb00"},\
    {"rlc c","cb01"},\
    {"rlc d","cb02"},\
    {"rlc e","cb03"},\
    {"rlc h","cb04"},\
    {"rlc l","cb05"},\
    {"rlc (hl)","cb06"},\
    {"rlc (ix+%i)","ddcb%b06"},\
    {"rlc (iy+%i)","fdcb%b06"},\
    {"rl a","cb17"},\
    {"rl b","cb10"},\
    {"rl c","cb11"},\
    {"rl d","cb12"},\
    {"rl e","cb13"},\
    {"rl h","cb14"},\
    {"rl l","cb15"},\
    {"rl (hl)","cb16"},\
    {"rl (ix+%i)","ddcb%b16"},\
    {"rl (iy+%i)","fdcb%b16"},\
    {"rrc a","cb0f"},\
    {"rrc b","cb08"},\
    {"rrc c","cb09"},\
    {"rrc d","cb0a"},\
    {"rrc e","cb0b"},\
    {"rrc h","cb0c"},\
    {"rrc l","cb0d"},\
    {"rrc (hl)","cb0e"},\
    {"rrc (ix+%i)","ddcb%b0e"},\
    {"rrc (iy+%i)","fdcb%b0e"},\
    {"rl a","cb1f"},\
    {"rl b","cb18"},\
    {"rl c","cb19"},\
    {"rl d","cb1a"},\
    {"rl e","cb1b"},\
    {"rl h","cb1c"},\
    {"rl l","cb1d"},\
    {"rl (hl)","cb1e"},\
    {"rl (ix+%i)","ddcb%b1e"},\
    {"rl (iy+%i)","fdcb%b1e"},\
    {"and a","a7"},\
    {"and b","a0"},\
    {"and c","a1"},\
    {"and d","a2"},\
    {"and e","a3"},\
    {"and h","a4"},\
    {"and l","a5"},\
    {"and (hl)","a6"},\
    {"and (ix+%i)","dda6%b"},\
    {"and (iy+%i)","fda6%b"},\
    {"and %i","e6%b"},\
    {"xor a","af"},\
    {"xor b","a8"},\
    {"xor c","a9"},\
    {"xor d","aa"},\
    {"xor e","ab"},\
    {"xor h","ac"},\
    {"xor l","ad"},\
    {"xor (hl)","ae"},\
    {"xor (ix+%i)","ddae%b"},\
    {"xor (iy+%i)","fdae%b"},\
    {"xor %i","ee%b"},\
    {"or a","b7"},\
    {"or b","b0"},\
    {"or c","b1"},\
    {"or d","b2"},\
    {"or e","b3"},\
    {"or h","b4"},\
    {"or l","b5"},\
    {"or (hl)","b6"},\
    {"or (ix+%i)","ddb6%b"},\
    {"or (iy+%i)","fdb6%b"},\
    {"or %i","f6%b"},\
    {"cp a","bf"},\
    {"cp b","b8"},\
    {"cp c","b9"},\
    {"cp d","ba"},\
    {"cp e","bb"},\
    {"cp h","bc"},\
    {"cp l","bd"},\
    {"cp (hl)","be"},\
    {"cp (ix+%i)","ddbe%b"},\
    {"cp (iy+%i)","fdbe%b"},\
    {"cp %i","fe%b"},\
    {"cpi","eda1"},\
    {"cpir","edb1"},\
    {"cpd","eda9"},\
    {"cpdr","edb9"},\
    {"jp %i","c3%w"},\
    {"jp nz,%i","c2%w"},\
    {"jp z,%i","ca%w"},\
    {"jp nc,%i","d2%w"},\
    {"jp c,%i","da%w"},\
    {"jp po,%i","e2%w"},\
    {"jp pe,%i","ea%w"},\
    {"jp p,%i","f2%w"},\
    {"jp m,%i","fa%w"},\
    {"jp (hl)","e9"},\
    {"jp (ix)","dde9"},\
    {"jp (iy)","fde9"},\
    {"jr %i","18%b"},\
    {"jr nz,%i","20%b"},\
    {"jr z,%i","28%b"},\
    {"jr nc,%i","30%b"},\
    {"jr c,%i","38%b"},\
    {"djnz %i","10%b"},\
    {"call %i","cd%w"},\
    {"call nz,%i","c4%w"},\
    {"call z,%i","cc%w"},\
    {"call nc,%i","d4%w"},\
    {"call c,%i","dc%w"},\
    {"call po,%i","e4%w"},\
    {"call pe,%i","ec%w"},\
    {"call p,%i","f4%w"},\
    {"call m,%i","fc%w"},\
    {"ret","c9"},\
    {"ret nz","c0"},\
    {"ret z","c8"},\
    {"ret nc","d0"},\
    {"ret c","d8"},\
    {"ret po","e0"},\
    {"ret pe","e8"},\
    {"ret p","f0"},\
    {"ret m","f8"},\
    {"reti","ed4d"},\
    {"retn","ed45"},\
    {"rst 0","c7"},\
    {"rst 8","cf"},\
    {"rst 10h","d7"},\
    {"rst 18h","df"},\
    {"rst 20h","e7"},\
    {"rst 28h","ef"},\
    {"rst 30h","f7"},\
    {"rst 38h","ff"},\
    {"push bc","c5"},\
    {"push de","d5"},\
    {"push hl","e5"},\
    {"push af","f5"},\
    {"push ix","dde5"},\
    {"push iy","fde5"},\
    {"pop bc","c1"},\
    {"pop de","d1"},\
    {"pop hl","e1"},\
    {"pop af","f1"},\
    {"pop ix","dde1"},\
    {"pop iy","fde1"},\
    {"in a,(%i)","db%b"},\
    {"in a,(c)","ed78"},\
    {"in b,(c)","ed40"},\
    {"in c,(c)","ed48"},\
    {"in d,(c)","ed50"},\
    {"in e,(c)","ed58"},\
    {"in h,(c)","ed60"},\
    {"in l,(c)","ed68"},\
    {"ini","eda2"},\
    {"inir","edb2"},\
    {"ind","edaa"},\
    {"indr","edba"},\
    {"out (%i),a","d3%b"},\
    {"out (c),a","ed79"},\
    {"out (c),b","ed41"},\
    {"out (c),c","ed49"},\
    {"out (c),d","ed51"},\
    {"out (c),e","ed59"},\
    {"out (c),h","ed61"},\
    {"out (c),l","ed69"},\
    {"outi","eda3"},\
    {"otir","edb3"},\
    {"outd","edab"},\
    {"otdr","edbb"},\
    {"ldi","eda0"},\
    {"ldir","edb0"},\
    {"ldd","eda8"},\
    {"lddr","edb8"},\
    {"bit 0,a","cb47"},\
    {"bit 0,b","cb40"},\
    {"bit 0,c","cb41"},\
    {"bit 0,d","cb42"},\
    {"bit 0,e","cb43"},\
    {"bit 0,h","cb44"},\
    {"bit 0,l","cb45"},\
    {"bit 0,(hl)","cb46"},\
    {"bit 0,(ix+%i)","ddcb%b46"},\
    {"bit 0,(iy+%i)","fdcb%b46"},\
    {"bit 1,a","cb4f"},\
    {"bit 1,b","cb48"},\
    {"bit 1,c","cb49"},\
    {"bit 1,d","cb4a"},\
    {"bit 1,e","cb4b"},\
    {"bit 1,h","cb4c"},\
    {"bit 1,l","cb4d"},\
    {"bit 1,(hl)","cb4e"},\
    {"bit 1,(ix+%i)","ddcb%b4e"},\
    {"bit 1,(iy+%i)","fdcb%b4e"},\
    {"bit 2,a","cb57"},\
    {"bit 2,b","cb50"},\
    {"bit 2,c","cb51"},\
    {"bit 2,d","cb52"},\
    {"bit 2,e","cb53"},\
    {"bit 2,h","cb54"},\
    {"bit 2,l","cb55"},\
    {"bit 2,(hl)","cb56"},\
    {"bit 2,(ix+%i)","ddcb%b56"},\
    {"bit 2,(iy+%i)","fdcb%b56"},\
    {"bit 3,a","cb5f"},\
    {"bit 3,b","cb58"},\
    {"bit 3,c","cb59"},\
    {"bit 3,d","cb5a"},\
    {"bit 3,e","cb5b"},\
    {"bit 3,h","cb5c"},\
    {"bit 3,l","cb5d"},\
    {"bit 3,(hl)","cb5e"},\
    {"bit 3,(ix+%i)","ddcb%b5e"},\
    {"bit 3,(iy+%i)","fdcb%b5e"},\
    {"bit 4,a","cb67"},\
    {"bit 4,b","cb60"},\
    {"bit 4,c","cb61"},\
    {"bit 4,d","cb62"},\
    {"bit 4,e","cb63"},\
    {"bit 4,h","cb64"},\
    {"bit 4,l","cb65"},\
    {"bit 4,(hl)","cb66"},\
    {"bit 4,(ix+%i)","ddcb%b66"},\
    {"bit 4,(iy+%i)","fdcb%b66"},\
    {"bit 5,a","cb6f"},\
    {"bit 5,b","cb68"},\
    {"bit 5,c","cb69"},\
    {"bit 5,d","cb6a"},\
    {"bit 5,e","cb6b"},\
    {"bit 5,h","cb6c"},\
    {"bit 5,l","cb6d"},\
    {"bit 5,(hl)","cb6e"},\
    {"bit 5,(ix+%i)","ddcb%b6e"},\
    {"bit 5,(iy+%i)","fdcb%b6e"},\
    {"bit 6,a","cb77"},\
    {"bit 6,b","cb70"},\
    {"bit 6,c","cb71"},\
    {"bit 6,d","cb72"},\
    {"bit 6,e","cb73"},\
    {"bit 6,h","cb74"},\
    {"bit 6,l","cb75"},\
    {"bit 6,(hl)","cb76"},\
    {"bit 6,(ix+%i)","ddcb%b76"},\
    {"bit 6,(iy+%i)","fdcb%b76"},\
    {"bit 7,a","cb7f"},\
    {"bit 7,b","cb78"},\
    {"bit 7,c","cb79"},\
    {"bit 7,d","cb7a"},\
    {"bit 7,e","cb7b"},\
    {"bit 7,h","cb7c"},\
    {"bit 7,l","cb7d"},\
    {"bit 7,(hl)","cb7e"},\
    {"bit 7,(ix+%i)","ddcb%b7e"},\
    {"bit 7,(iy+%i)","fdcb%b7e"},\
    {"res 0,a","cb87"},\
    {"res 0,b","cb80"},\
    {"res 0,c","cb81"},\
    {"res 0,d","cb82"},\
    {"res 0,e","cb83"},\
    {"res 0,h","cb84"},\
    {"res 0,l","cb85"},\
    {"res 0,(hl)","cb86"},\
    {"res 0,(ix+%i)","ddcb%b86"},\
    {"res 0,(iy+%i)","fdcb%b86"},\
    {"res 1,a","cb8f"},\
    {"res 1,b","cb88"},\
    {"res 1,c","cb89"},\
    {"res 1,d","cb8a"},\
    {"res 1,e","cb8b"},\
    {"res 1,h","cb8c"},\
    {"res 1,l","cb8d"},\
    {"res 1,(hl)","cb8e"},\
    {"res 1,(ix+%i)","ddcb%b8e"},\
    {"res 1,(iy+%i)","fdcb%b8e"},\
    {"res 2,a","cb97"},\
    {"res 2,b","cb90"},\
    {"res 2,c","cb91"},\
    {"res 2,d","cb92"},\
    {"res 2,e","cb93"},\
    {"res 2,h","cb94"},\
    {"res 2,l","cb95"},\
    {"res 2,(hl)","cb96"},\
    {"res 2,(ix+%i)","ddcb%b96"},\
    {"res 2,(iy+%i)","fdcb%b96"},\
    {"res 3,a","cb9f"},\
    {"res 3,b","cb98"},\
    {"res 3,c","cb99"},\
    {"res 3,d","cb9a"},\
    {"res 3,e","cb9b"},\
    {"res 3,h","cb9c"},\
    {"res 3,l","cb9d"},\
    {"res 3,(hl)","cb9e"},\
    {"res 3,(ix+%i)","ddcb%b9e"},\
    {"res 3,(iy+%i)","fdcb%b9e"},\
    {"res 4,a","cba7"},\
    {"res 4,b","cba0"},\
    {"res 4,c","cba1"},\
    {"res 4,d","cba2"},\
    {"res 4,e","cba3"},\
    {"res 4,h","cba4"},\
    {"res 4,l","cba5"},\
    {"res 4,(hl)","cba6"},\
    {"res 4,(ix+%i)","ddcb%ba6"},\
    {"res 4,(iy+%i)","fdcb%ba6"},\
    {"res 5,a","cbaf"},\
    {"res 5,b","cba8"},\
    {"res 5,c","cba9"},\
    {"res 5,d","cbaa"},\
    {"res 5,e","cbab"},\
    {"res 5,h","cbac"},\
    {"res 5,l","cbad"},\
    {"res 5,(hl)","cbae"},\
    {"res 5,(ix+%i)","ddcb%bae"},\
    {"res 5,(iy+%i)","fdcb%bae"},\
    {"res 6,a","cbb7"},\
    {"res 6,b","cbb0"},\
    {"res 6,c","cbb1"},\
    {"res 6,d","cbb2"},\
    {"res 6,e","cbb3"},\
    {"res 6,h","cbb4"},\
    {"res 6,l","cbb5"},\
    {"res 6,(hl)","cbb6"},\
    {"res 6,(ix+%i)","ddcb%bb6"},\
    {"res 6,(iy+%i)","fdcb%bb6"},\
    {"res 7,a","cbbf"},\
    {"res 7,b","cbb8"},\
    {"res 7,c","cbb9"},\
    {"res 7,d","cbba"},\
    {"res 7,e","cbbb"},\
    {"res 7,h","cbbc"},\
    {"res 7,l","cbbd"},\
    {"res 7,(hl)","cbbe"},\
    {"res 7,(ix+%i)","ddcb%bbe"},\
    {"res 7,(iy+%i)","fdcb%bbe"},\
    {"set 0,a","cbc7"},\
    {"set 0,b","cbc0"},\
    {"set 0,c","cbc1"},\
    {"set 0,d","cbc2"},\
    {"set 0,e","cbc3"},\
    {"set 0,h","cbc4"},\
    {"set 0,l","cbc5"},\
    {"set 0,(hl)","cbc6"},\
    {"set 0,(ix+%i)","ddcb%bc6"},\
    {"set 0,(iy+%i)","fdcb%bc6"},\
    {"set 1,a","cbcf"},\
    {"set 1,b","cbc8"},\
    {"set 1,c","cbc9"},\
    {"set 1,d","cbca"},\
    {"set 1,e","cbcb"},\
    {"set 1,h","cbcc"},\
    {"set 1,l","cbcd"},\
    {"set 1,(hl)","cbce"},\
    {"set 1,(ix+%i)","ddcb%bce"},\
    {"set 1,(iy+%i)","fdcb%bce"},\
    {"set 2,a","cbd7"},\
    {"set 2,b","cbd0"},\
    {"set 2,c","cbd1"},\
    {"set 2,d","cbd2"},\
    {"set 2,e","cbd3"},\
    {"set 2,h","cbd4"},\
    {"set 2,l","cbd5"},\
    {"set 2,(hl)","cbd6"},\
    {"set 2,(ix+%i)","ddcb%bd6"},\
    {"set 2,(iy+%i)","fdcb%bd6"},\
    {"set 3,a","cbdf"},\
    {"set 3,b","cbd8"},\
    {"set 3,c","cbd9"},\
    {"set 3,d","cbda"},\
    {"set 3,e","cbdb"},\
    {"set 3,h","cbdc"},\
    {"set 3,l","cbdd"},\
    {"set 3,(hl)","cbde"},\
    {"set 3,(ix+%i)","ddcb%bde"},\
    {"set 3,(iy+%i)","fdcb%bde"},\
    {"set 4,a","cbe7"},\
    {"set 4,b","cbe0"},\
    {"set 4,c","cbe1"},\
    {"set 4,d","cbe2"},\
    {"set 4,e","cbe3"},\
    {"set 4,h","cbe4"},\
    {"set 4,l","cbe5"},\
    {"set 4,(hl)","cbe6"},\
    {"set 4,(ix+%i)","ddcb%be6"},\
    {"set 4,(iy+%i)","fdcb%be6"},\
    {"set 5,a","cbef"},\
    {"set 5,b","cbe8"},\
    {"set 5,c","cbe9"},\
    {"set 5,d","cbea"},\
    {"set 5,e","cbeb"},\
    {"set 5,h","cbec"},\
    {"set 5,l","cbed"},\
    {"set 5,(hl)","cbee"},\
    {"set 5,(ix+%i)","ddcb%bee"},\
    {"set 5,(iy+%i)","fdcb%bee"},\
    {"set 6,a","cbf7"},\
    {"set 6,b","cbf0"},\
    {"set 6,c","cbf1"},\
    {"set 6,d","cbf2"},\
    {"set 6,e","cbf3"},\
    {"set 6,h","cbf4"},\
    {"set 6,l","cbf5"},\
    {"set 6,(hl)","cbf6"},\
    {"set 6,(ix+%i)","ddcb%bf6"},\
    {"set 6,(iy+%i)","fdcb%bf6"},\
    {"set 7,a","cbff"},\
    {"set 7,b","cbf8"},\
    {"set 7,c","cbf9"},\
    {"set 7,d","cbfa"},\
    {"set 7,e","cbfb"},\
    {"set 7,h","cbfc"},\
    {"set 7,l","cbfd"},\
    {"set 7,(hl)","cbfe"},\
    {"set 7,(ix+%i)","ddcb%bfe"},\
    {"set 7,(iy+%i)","fdcb%bfe"},\
    {"sla a","cb27"},\
    {"sla b","cb20"},\
    {"sla c","cb21"},\
    {"sla d","cb22"},\
    {"sla e","cb23"},\
    {"sla h","cb24"},\
    {"sla l","cb25"},\
    {"sla (hl)","cb26"},\
    {"sla (ix+%i)","ddcb%b26"},\
    {"sla (iy+%i)","fdcb%b26"},\
    {"sra a","cb2f"},\
    {"sra b","cb28"},\
    {"sra c","cb29"},\
    {"sra d","cb2a"},\
    {"sra e","cb2b"},\
    {"sra h","cb2c"},\
    {"sra l","cb2d"},\
    {"sra (hl)","cb2e"},\
    {"sra (ix+%i)","ddcb%b2e"},\
    {"sra (iy+%i)","fdcb%b2e"},\
    {"srl a","cb3f"},\
    {"srl b","cb38"},\
    {"srl c","cb39"},\
    {"srl d","cb3a"},\
    {"srl e","cb3b"},\
    {"srl h","cb3c"},\
    {"srl l","cb3d"},\
    {"srl (hl)","cb3e"},\
    {"srl (ix+%i)","ddcb%b3e"},\
    {"srl (iy+%i)","fdcb%b3e"}
};

class InstructionTable {
public:
    InstructionTable() {
    }
    
    EscapedBinary getBinary(string normalInstruction) {
        try {
            return EscapedBinary(z80instructions.at(normalInstruction));
        }
        catch (out_of_range e) {
            throw new InstructionNotRecognizedException(normalInstruction);
        }
    }
};

#endif /* InstructionTable_h */
